chore: nginx container
domain name, application path based routing, and internal dns all are configured in this commit

diff --git a/run_app b/run_app
--- a/run_app
+++ b/run_app
@@ -14,7 +14,7 @@ fi
 # Spin up Laravel app
 echo "Starting Laravel application..."
 cd $LARAVEL_APP_PATH || { echo "Failed to change directory to $LARAVEL_APP_PATH"; exit 1; }
-./vendor/bin/sail up -d || { echo "Failed to start Laravel application"; exit 1; }
+./vendor/bin/sail up -d --build || { echo "Failed to start Laravel application"; exit 1; }
 
 echo "Building Laravel assets..."
 ./vendor/bin/sail npm run build || { echo "Failed to build Laravel assets"; exit 1; }
@@ -26,6 +26,11 @@ cd - || { echo "Failed to return to the initial directory"; exit 1; }
 
 # Spin up Node.js app
 echo "Starting Node.js application..."
-docker-compose -f $NODE_APP_PATH/docker-compose.yml up -d || { echo "Failed to start Node.js application"; exit 1; }
+docker-compose -f $NODE_APP_PATH/docker-compose.yml up -d --build || { echo "Failed to start Node.js application"; exit 1; }
+
+echo "Starting other componentns"
+docker-compose up -d --build
 
 echo "All services started successfully."
+
+
