fix: run app script

diff --git a/run_app b/run_app
--- a/run_app
+++ b/run_app
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+./stop_app
+
 LARAVEL_APP_PATH="./blogs"
 NODE_APP_PATH="./editor"
 
@@ -14,7 +16,15 @@ fi
 # Spin up Laravel app
 echo "Starting Laravel application..."
 cd $LARAVEL_APP_PATH || { echo "Failed to change directory to $LARAVEL_APP_PATH"; exit 1; }
+
+echo "check composer packages..."
+composer update || { echo "Failed to change directory to $LARAVEL_APP_PATH"; exit 1; }
+
+echo "Starting Laravel application..."
 ./vendor/bin/sail up -d --build || { echo "Failed to start Laravel application"; exit 1; }
+
+echo "Installing Node packages..."
+./vendor/bin/sail npm install || { echo "Failed to build Laravel assets"; exit 1; }
 
 echo "Building Laravel assets..."
 ./vendor/bin/sail npm run build || { echo "Failed to build Laravel assets"; exit 1; }
