feat: stop app script

diff --git a/run_app b/run_app
--- a/run_app
+++ b/run_app
@@ -5,6 +5,12 @@ NODE_APP_PATH="./editor"
 
 export APP_PORT=8000
 
+echo "Creating application network if doesn't exist..."
+docker network inspect blogs_app > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+    docker network create blogs_app || { echo "Failed to create network"; exit 1; }
+fi
+
 # Spin up Laravel app
 echo "Starting Laravel application..."
 cd $LARAVEL_APP_PATH || { echo "Failed to change directory to $LARAVEL_APP_PATH"; exit 1; }
